### ISSUE TITLE
Datatype Discrepancy Issue

### ISSUE THREAD

**Issue by KpEssex** [udacity/robot_pose_ekf#1]
Hi, I just have a small question (I'm new to GitHub, so I'm not sure if this is the right place, but I'll give it a try). I am trying to have the "robot_pose_ekf" work with "fiducial_slam/fiducial_pose" so that a robot equipped with a camera (which would detect fiducials) would be able to determine its own position in a network of fiducials. However, when I tried running the two programs together, I got this error:

**[ERROR] [1389688193.050254972]: Client [/robot_pose_ekf] wants topic /fiducial_pose to have datatype/md5sum [nav_msgs/Odometry/cd5e73d190d741a2f92e81eda573aca7], but our version has [geometry_msgs/PoseWithCovarianceStamped/953b798c0f514ff060a53a3498ce6246]. Dropping connection.**

Based on what I've been looking up to fix the issue, I believe that in order to fix this I would have to alter the message type from to "geometry_msgs::PoseWithCovarianceStamped" instead of "nav_msgs::odometry":

**robot.OdomCombinedSubscriber = nh.subscribe<geometry_msgs::PoseWithCovarianceStamped>("/robot_pose_ekf/odom_combined"[...]&robot);**

However, when I tried looking for the abovementioned piece, I could not find it, despite looking through what seemed to be all the folders and texts. Where could I change the message type so that the error can be addressed, and if this is no longer the way to fix the error (or any other way to do so), what would that method be?

Thank you very much for your help, and I look forward to your reply! Have a great day!

**Comment by karimchamaa** [comment]
Hey KpEssex, I see that you want a conversion between **nav_msgs/Odometry/** and **geometry_msgs/PoseWithCovarianceStamped**. 

I believe you will need to write a node that will subscribe to **geometry_msgs/PoseWithCovarianceStamped** messages and publish  **nav_msgs/Odometry/** messages. To help you get started take a look at the [odom_to_trajectory](https://github.com/udacity/odom_to_trajectory) package and specifically the [path_ekf_plotter.py](https://github.com/udacity/odom_to_trajectory/blob/master/scripts/path_ekf_plotter.py) script where it's dealing with these 2 types of messages. Hope that helps!

**Comment by KpEssex** [comment]
I think I got it to work. Thank you very much for your help, and have a great summer!

- Kp

**Comment by karimchamaa** [comment]
Glad it worked for you. Thanks, you're welcome!
