### ISSUE TITLE
MIT License is invalid -- Seemingly illegal relicense

### ISSUE THREAD

**Issue by SteveMacenski** [udacity/robot_pose_ekf#5]
Hi @karimchamaa,

It looks like you copy pasted this from the navigation stack / ros-planning work and may have accidentally illegally relicensed it under MIT. 

You are more than welcome under the rights of BSD to copy paste this around as long as you retain the original copyright headers, but you may not relicense the project under MIT, which you included in the root of this package. 

Also, you continue to have the license listed as BSD in the package.xml. 

Given all you've done to this is add a nice README, I **strongly** recommend submitting a PR against the robot_pose_ekf package in ros-planning that I would merge and archiving this repository. If nothing else, please respond to change the licensing.

**Comment by rbUdacProjects** [comment]
Hi Steve,
Thank you for bringing this to our attention. We have now removed the Udacity license and replaced it with the BSD license that now appears in the master branch.
