### ISSUE TITLE
sensor data without covariance

### ISSUE THREAD

**Issue by TBetterman** [udacity/robot_pose_ekf#7]
hi, i achieved amazing performance when run this demo project. But when i apply our own sensor data to this work, it perform not well. The odom data and vo data don't have corresponding covariance, what should i do? if the covariance is necessary, can you teach me how to figure it out? Thank you so much~

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
